import {colors} from '../colors';

export const MuiTypography = {
  fontFamily: ['gordita', 'Arial', 'Sans-Serif'].join(','),
  root: {
    color: colors.grey56,
    fontFamily: ['gordita', 'Arial', 'Sans-Serif'].join(','),
    // fontStyle: "Regular",
  },
  h1: {
    // fontStyle: "Regular",
    // marginBottom: 48,
    fontWeight: 400,
    fontSize: 36,
    lineHeight: '40px',
    color: colors.grey56,
  },
  h2: {
    // fontStyle: "Regular",
    // marginBottom: 24,
    fontWeight: 400,
    fontSize: 24,
    lineHeight: '28px',
    color: colors.grey56,
  },
  h3: {
    // fontStyle: "Medium",
    // marginBottom: 16,
    fontWeight: 600,
    fontSize: 18,
    lineHeight: '24px',
    color: colors.grey56,
  },
  h4: {
    // fontStyle: "Medium",
    // marginBottom: 16,
    fontWeight: 600,
    fontSize: 16,
    lineHeight: '24px',
    color: colors.grey56,
  },
  h5: {
    // fontStyle: "Regular",
    // marginBottom: 64,
    fontWeight: 400,
    fontSize: 56,
    lineHeight: '64px',
    color: colors.grey56,
  },
  h6: {
    // fontStyle: "Regular",
    // marginBottom: 32,
    fontWeight: 400,
    fontSize: 32,
    lineHeight: '40px',
    color: colors.grey56,
  },
  subtitle1: {
    // fontStyle: "Medium",
    // marginBottom: 24,
    fontWeight: 600,
    fontSize: 20,
    lineHeight: '28px',
    color: colors.grey56,
  },
  subtitle2: {
    // fontStyle: "Medium",
    // marginBottom: 24,
    fontWeight: 600,
    fontSize: 20,
    lineHeight: '28px',
    color: colors.grey56,
  },
  body1: {
    // fontStyle: "Regular",
    // marginBottom: 48,
    fontWeight: 400,
    fontSize: 18,
    lineHeight: '24px',
    color: colors.grey56,
  },
  body2: {
    // fontStyle: "Regular",
    // marginBottom: 16,
    fontWeight: 400,
    fontSize: 14,
    lineHeight: '24px',
    color: colors.grey,
  },
  caption: {
    // fontStyle: "Regular",
    // marginBottom: 16,
    fontWeight: 400,
    fontSize: 12,
    lineHeight: '20px',
    color: colors.grey80,
  },
  overline: {
    // fontStyle: "Regular",
    // marginBottom: 64,
    fontSize: 20,
    lineHeight: '28px',
    color: '#232323',
    textTransform: 'none',
  },
  colorTextSecondary: {
    color: `${colors.white} !important`,
  },
  // button: {},
  // alignCenter: {},
  // alignJustify: {},
  // alignRight: {},
  // alignLeft: {},
  // noWrap: {},
  // paragraph: {},
  // colorInherit: {},
  // colorPrimary: {},
  // colorSecondary: {},
  // colorTextPrimary: {},
  // colorError: {},
  // displayInline: {},
  // displayBlock: {},
  // gutterBottom: {},
  // srOnly: {}
};
