import { Color } from "@origin-digital/ods-types";
import { Palette } from "@material-ui/core/styles/createPalette";

export function flattenPalette(palette: Palette): Color {
  return {
    backgroundDefault: palette.background.default,
    backgroundPaper: palette.background.paper,
    backgroundLight: palette.background.light,
    caution: palette.caution.main,
    cautionDark: palette.caution.dark,
    cautionLight: palette.caution.light,
    critical: palette.critical.main,
    criticalDark: palette.critical.dark,
    criticalLight: palette.critical.light,
    grey100: palette.grey[100],
    grey200: palette.grey[200],
    grey300: palette.grey[300],
    grey400: palette.grey[400],
    grey50: palette.grey[50],
    grey500: palette.grey[500],
    grey600: palette.grey[600],
    info: palette.info.main,
    infoDark: palette.info.light,
    infoLight: palette.info.dark,
    positive: palette.positive.main,
    positiveDark: palette.positive.light,
    positiveLight: palette.positive.dark,
    primary: palette.primary.main,
    primaryDark: palette.primary.light,
    primaryLight: palette.primary.dark,
    primaryB: palette.primaryB.main,
    primaryBDark: palette.primaryB.light,
    primaryBLight: palette.primaryB.dark,
    promote: palette.promote.main,
    promoteDark: palette.promote.light,
    promoteLight: palette.promote.dark,
    promoteB: palette.promoteB.main,
    promoteBDark: palette.promoteB.light,
    promoteBLight: palette.promoteB.dark,
    secondary: palette.secondary.main,
    secondaryDark: palette.secondary.light,
    secondaryLight: palette.secondary.dark,
    secondaryB: palette.secondaryB.main,
    secondaryBDark: palette.secondaryB.light,
    secondaryBLight: palette.secondaryB.dark,
    white: "#FFFFFF",
    transparent: "transparent",
  };
}
