import { Colors } from "@origin-digital/ods-types";
import { Palette } from "@material-ui/core/styles/createPalette";
import { palette } from "../core/palette";

function flattenPalette(palette: Palette): Colors {
  return {
    backgroundDefault: palette.background.default,
    backgroundPaper: palette.background.paper,
    caution: palette.secondary.main,
    cautionDark: palette.secondary.dark,
    cautionLight: palette.secondary.light,
    critical: palette.error.main,
    criticalDark: palette.error.dark,
    criticalLight: palette.error.light,
    grey100: palette.grey[100],
    grey200: palette.grey[200],
    grey300: palette.grey[300],
    grey400: palette.grey[400],
    grey50: palette.grey[50],
    grey500: palette.grey[500],
    grey600: palette.grey[600],
    info: palette.info.main,
    infoDark: palette.info.dark,
    infoLight: palette.info.light,
    positive: palette.success.main,
    positiveDark: palette.success.dark,
    positiveLight: palette.success.light,
    primary: palette.primary.main,
    primaryDark: palette.primary.dark,
    primaryLight: palette.primary.light,
    primaryB: palette.primaryB.main,
    primaryBDark: palette.primaryB.dark,
    primaryBLight: palette.primaryB.light,
    promote: palette.info.main,
    promoteDark: palette.info.dark,
    promoteLight: palette.info.light,
    promoteB: palette.promoteB.main,
    promoteBDark: palette.promoteB.dark,
    promoteBLight: palette.promoteB.light,
    secondary: palette.secondary.main,
    secondaryDark: palette.secondary.dark,
    secondaryLight: palette.secondary.light,
    secondaryB: palette.secondaryB.main,
    secondaryBDark: palette.secondaryB.dark,
    secondaryBLight: palette.secondaryB.light,
    white: "#FFFFFF",
    transparent: "transparent",
  };
}

export const colors = {
  ...flattenPalette(palette),
  darkRed: "#b30000",
  veryDarkRed: "#7b0000",
  redBackground: "#feebeb",
  redBorder: "#fcd6d6",
  mediumBlue: "#2275D3",
  darkGrey: "#3c3c3c",
  // For TextField
  greyHover: "#EAEAEA",
  greyDisabled: "#F8F8F8",
  greyTextField: "#666666",
  greyTextDisabled: "#9D9D9D",
  greyIcon: "#d6d6d6",
  black: "#232323",
  // For segmented controls
  yellow: "#FFF9EF",
  yellow16: "#FFF3DF",
  yellow24: "#FFEECE",
  yellow32: "#FFE7BE",
};
